nelmio_cors:
    defaults:
        allow_origin: ['http://127.0.0.1:44019'] # Angular dev server
        allow_credentials: true
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'OPTIONS']
        max_age: 3600
    paths:
        '^/api/v1/login_check':
            allow_origin: ['http://127.0.0.1:44019', 'http://localhost:4200', 'http://localhost']
            allow_credentials: true
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'POST', 'OPTIONS']
